###
POST http://localhost:8080/usuario
Content-Type: application/json

{
  "cuentaMail": "maria@mail.com",
  "password": "coso",
  "apellido": "Diaz",
  "cedula": 123456888,
  "nombre": "Juan",
  "saldo": 1.00,
  "saldo_base": 1.00,
  "sobregiro": 2.00,
  "telefono": "097 824 674",
  "vencimientoCarne": "02/07/2002"
}

###
GET http://localhost:8080/usuario/all

###
POST http://localhost:8080/cuenta
Content-Type: application/json

{
  "mail": "maria@mail.com",
  "password": "Contrasena",
  "entidadPadre": null,
  "tipo": "usuario"
}

###
GET http://localhost:8080/empresa/empresa/usuarios
Content-Type: application/json

