###
GET http://localhost:8080/servicio/canchas


###
POST http://localhost:8080/centro/postActividad/centro@mail
Content-Type: application/json

{
    "nombreServicio": "pruebita",
    "precio": 1000,
    "cupos": 10,
    "paseLibre": true,
    "imagen": "fotito",
    "horarios": [
      {
        "dia": 1,
        "horaInicio": 1000,
        "horaFin": 1100
      }
    ]
}


###
GET http://localhost:8080/servicio/actividad/centro/Tenis
Content-Type: application/json


###
GET http://localhost:8080/servicio/cancha/centro/cancha_Fuchibol
Content-Type: application/json


###
GET http://localhost:8080/centro/balance/bella@vista.com/11/2022
Content-Type: application/json

