###
GET http://localhost:8080/servicio/canchas

###
GET http://localhost:8080/servicio/canchas/0/9

###
POST http://localhost:8080/centro/postActividad/centro@mail
Content-Type: application/json

{
    "nombreServicio": "pruebita",
    "precio": 1000,
    "cupos": 10,
    "paseLibre": true,
    "imagen": "fotito",
    "horarios": [
      {
        "dia": 1,
        "horaInicio": 1000,
        "horaFin": 1100
      }
    ]
}


###
GET http://localhost:8080/servicio/actividad/centro/Tenis
Content-Type: application/json


###
GET http://localhost:8080/servicio/cancha/centro/cancha_Fuchibol
Content-Type: application/json


###
GET http://localhost:8080/centro/balance/bella@vista.com/11/2022
Content-Type: application/json

###
POST http://localhost:8080/centro/checkIn
Content-Type: application/json

{
  "cedulaUsuario": 12344321,
  "nombreCentro": "CA Bella Vista ",
  "nombreActividad": "Otra actividad cara",
  "paseLibre": false,
  "tipo": "Actividad",
  "horario":
    {
      "dia": 3,
      "horaInicio": 1102,
      "horaFin": 1200
    },
  "codigoCheckIn": null,
  "checkInCanchaPadre": null,
  "fecha": "2022-11-15",
  "precio": 5000
}