###
POST http://localhost:8080/usuario
Content-Type: application/json

{
  "cuentaMail": "maria@mail.com",
  "password": "coso",
  "apellido": "Diaz",
  "cedula": 52788472,
  "nombre": "Juan",
  "saldo": 1.00,
  "saldo_base": 1.00,
  "sobregiro": 2.00,
  "telefono": "097 824 674",
  "vencimientoCarne": "02/07/2002"
}

###
GET http://localhost:8080/usuario/id/123456888


###
GET http://localhost:8080/usuario/all

###
GET http://localhost:8080/usuario/intenta

###
POST http://localhost:8080/usuario/reserva
Content-Type: application/json

{
  "cedulaUsuario": "52788472",
  "nombreCentro": "CanchasVarias",
  "nombreActividad": "LaCanchita",
  "tipo": "Cancha",
  "horario":
      {"dia": 3,
       "horaInicio": 1430,
       "horaFin": 1530
       },
  "codigoReserva": null,
  "codigoReservaPadre": null
}

###
POST http://localhost:8080/usuario/reserva
Content-Type: application/json

{
  "cedulaUsuario": "52788472",
  "nombreCentro": "CanchasVarias",
  "nombreActividad": "LaCanchita",
  "tipo": "Cancha",
  "horario":
    {"dia": 3,
    "horaInicio": 1430,
    "horaFin": 1530
  },
  "codigoReserva": null,
  "codigoReservaPadre": 6
}
