###
GET http://localhost:8080/cuenta/autenticar
Content-Type: application/json

{
  "mail": "admin",
  "password": "contra",
  "tipo": ""
}


###
POST http://localhost:8080/cuenta
Content-Type: application/json

{
  "mail": "maria@mail.com",
  "password": "Contrasena",
  "tipo": "usuario"
}


